### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by Reallyaravind** [evanch98/miro-clone-nextjs#1]
![image](https://github.com/evanch98/miro-clone-nextjs/assets/101699686/2590c177-bee3-4fe6-a083-fb8b0b3e37ab)
when I clone and deploy the application in vercel with all the instructions, it shows the above error

https://board-gbc4.vercel.app/

please check it out.

**Comment by evanch98** [comment]
Thank you so much for pointing out the issue. Since this is a simple hobby project, I mainly focus on the web application's functionality. I did not intend to optimize the application to be perfect and production-ready. I will try to find a solution to fix the warning. If you find a way to solve the issue, please do share it with me. Happy coding.

**Comment by Reallyaravind** [comment]
https://github.com/vercel/next.js/discussions/49607

seems like this issue is un-answered

**Comment by Reallyaravind** [comment]
Found the issue

convex/auth.config.js
```
export default {
  providers: [
    {
      domain: "https://quiet-llama-40.clerk.accounts.dev",
      applicationID: "convex",
    },
  ],
};
```
you need to change the domain to the CLERK_JWT_ISSUER_DOMAIN

If you can add this to the .env.local then anyone can change it there easily itself

Changed that and that solved the issue

if anyone wants you can check the repo here

https://github.com/Reallyaravind/board-application
